version: '3'
services:
  frontend:
    image: ${DOCKER_REGISTRY}/frontend:${BUILD_NUMBER}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ${DOCKER_REGISTRY}/backend:${BUILD_NUMBER}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 